"""updated db

Revision ID: 972d6edb1f9c
Revises: 8983162fea33
Create Date: 2023-05-17 18:37:22.993494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972d6edb1f9c'
down_revision = '8983162fea33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joined', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'joined')
    # ### end Alembic commands ###
