"""added indexes

Revision ID: f4df94d53ede
Revises: 2d1cc2f8ecd5
Create Date: 2023-05-17 16:53:31.487234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4df94d53ede'
down_revision = '2d1cc2f8ecd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_room_head'), 'room', ['head'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_head'), table_name='room')
    # ### end Alembic commands ###
